from __future__ import annotations

from app.services.research.templates.sports_nba_match_winner import (
    NBA_MATCH_WINNER_RESEARCH_INSTRUCTIONS,
    SPORTS_NBA_MATCH_WINNER_TEMPLATE,
)

NBA_WINNER_RESEARCH_INSTRUCTIONS = NBA_MATCH_WINNER_RESEARCH_INSTRUCTIONS
SPORTS_NBA_WINNER_TEMPLATE = SPORTS_NBA_MATCH_WINNER_TEMPLATE
